// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpichxqpfuonlbmqsoon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwaWNoeHFwZnVvbmxibXFzb29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTQwNTQsImV4cCI6MjA2OTk5MDA1NH0.HGDhH2yYR33c4yJrBjXb8vYbjlgW7sEbPdHSpqrOJC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});